In [ ]:
import numpy as np

In [4]:
out_pop_matrix = np.zeros(shape=(12, 12))

In [5]:
out_pop_matrix

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
l_m=np.array([[ 0.5,  2,  0.5,  2,  0.5,  2,  0.5,  2,  0.5,  2,  0.5,  0.],
       [ 0.8,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.8,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.8,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.8,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.8,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.8,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.8,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.2,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.2,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.2,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.2,  0.]])

In [7]:
out_pop_matrix[:, 0] = 120

In [9]:
for i in range(1, 12):
    n = np.dot(l_m, out_pop_matrix[:, i-1])
    out_pop_matrix[:, i] = n.squeeze()

In [10]:
out_pop_matrix

array([[  1.20000000e+02,   1.56000000e+03,   1.76400000e+03,
          3.97560000e+03,   5.75532000e+03,   1.16589720e+04,
          1.86230988e+04,   3.53490035e+04,   5.93273285e+04,
          1.08795100e+05,   1.87158394e+05,   3.36773432e+05],
       [  1.20000000e+02,   9.60000000e+01,   1.24800000e+03,
          1.41120000e+03,   3.18048000e+03,   4.60425600e+03,
          9.32717760e+03,   1.48984790e+04,   2.82792028e+04,
          4.74618628e+04,   8.70360803e+04,   1.49726715e+05],
       [  1.20000000e+02,   9.60000000e+01,   7.68000000e+01,
          9.98400000e+02,   1.12896000e+03,   2.54438400e+03,
          3.68340480e+03,   7.46174208e+03,   1.19187832e+04,
          2.26233622e+04,   3.79694902e+04,   6.96288643e+04],
       [  1.20000000e+02,   9.60000000e+01,   7.68000000e+01,
          6.14400000e+01,   7.98720000e+02,   9.03168000e+02,
          2.03550720e+03,   2.94672384e+03,   5.96939366e+03,
          9.53502659e+03,   1.80986898e+04,   3.03755922e+04],
    

In [ ]:
test_eig_vals = np.linalg.eigvals(l_m)

In [27]:
test_eig_vals

array([  0.00000000e+00+0.j        ,   1.76609846e+00+0.j        ,
        -1.25852532e+00+0.j        ,  -5.15086410e-01+0.54144808j,
        -5.15086410e-01-0.54144808j,   5.31081509e-01+0.54911554j,
         5.31081509e-01-0.54911554j,   9.69834682e-05+0.73307618j,
         9.69834682e-05-0.73307618j,   5.13868978e-03+0.20746092j,
         5.13868978e-03-0.20746092j,  -5.00346875e-02+0.j        ])

In [29]:
test_val, test_vec= np.linalg.eig(l_m)

In [30]:
test_vec

array([[  0.00000000e+00 +0.00000000e+00j,
         -8.91524103e-01 +0.00000000e+00j,
         -7.72229304e-01 +0.00000000e+00j,
         -2.21119261e-01 -1.54800265e-01j,
         -2.21119261e-01 +1.54800265e-01j,
          2.32013201e-01 -1.83263890e-01j,
          2.32013201e-01 +1.83263890e-01j,
          2.29878953e-04 +2.48228958e-01j,
          2.29878953e-04 -2.48228958e-01j,
         -6.49280704e-06 -3.70788399e-05j,
         -6.49280704e-06 +3.70788399e-05j,
         -1.41969943e-11 +0.00000000e+00j],
       [  0.00000000e+00 +0.00000000e+00j,
         -4.03838913e-01 +0.00000000e+00j,
          4.90878835e-01 +0.00000000e+00j,
          4.30872645e-02 +2.85718523e-01j,
          4.30872645e-02 -2.85718523e-01j,
          3.09606889e-02 -3.08073439e-01j,
          3.09606889e-02 +3.08073439e-01j,
          2.70890248e-01 -2.15027157e-04j,
          2.70890248e-01 +2.15027157e-04j,
         -1.43513602e-04 +2.14824738e-05j,
         -1.43513602e-04 -2.14824738e-05j,
          

In [33]:
test_vl = test_vec[0,:]

In [58]:
test_vl

array([  0.00000000e+00 +0.00000000e+00j,
        -8.91524103e-01 +0.00000000e+00j,
        -7.72229304e-01 +0.00000000e+00j,
        -2.21119261e-01 -1.54800265e-01j,
        -2.21119261e-01 +1.54800265e-01j,
         2.32013201e-01 -1.83263890e-01j,
         2.32013201e-01 +1.83263890e-01j,
         2.29878953e-04 +2.48228958e-01j,
         2.29878953e-04 -2.48228958e-01j,
        -6.49280704e-06 -3.70788399e-05j,
        -6.49280704e-06 +3.70788399e-05j,  -1.41969943e-11 +0.00000000e+00j])

In [59]:
test_vr = test_vec[1,:]

In [60]:
test_vr

array([  0.00000000e+00 +0.00000000e+00j,
        -4.03838913e-01 +0.00000000e+00j,
         4.90878835e-01 +0.00000000e+00j,
         4.30872645e-02 +2.85718523e-01j,
         4.30872645e-02 -2.85718523e-01j,
         3.09606889e-02 -3.08073439e-01j,
         3.09606889e-02 +3.08073439e-01j,
         2.70890248e-01 -2.15027157e-04j,
         2.70890248e-01 +2.15027157e-04j,
        -1.43513602e-04 +2.14824738e-05j,
        -1.43513602e-04 -2.14824738e-05j,   2.26995736e-10 +0.00000000e+00j])

In [40]:
test_val

array([  0.00000000e+00+0.j        ,   1.76609846e+00+0.j        ,
        -1.25852532e+00+0.j        ,  -5.15086410e-01+0.54144808j,
        -5.15086410e-01-0.54144808j,   5.31081509e-01+0.54911554j,
         5.31081509e-01-0.54911554j,   9.69834682e-05+0.73307618j,
         9.69834682e-05-0.73307618j,   5.13868978e-03+0.20746092j,
         5.13868978e-03-0.20746092j,  -5.00346875e-02+0.j        ])

In [42]:
test_eig_vals

array([  0.00000000e+00+0.j        ,   1.76609846e+00+0.j        ,
        -1.25852532e+00+0.j        ,  -5.15086410e-01+0.54144808j,
        -5.15086410e-01-0.54144808j,   5.31081509e-01+0.54911554j,
         5.31081509e-01-0.54911554j,   9.69834682e-05+0.73307618j,
         9.69834682e-05-0.73307618j,   5.13868978e-03+0.20746092j,
         5.13868978e-03-0.20746092j,  -5.00346875e-02+0.j        ])

In [71]:
for k in [0, 11]:
    prod = np.zeros(12)
    prod[k] = test_vl[k] * test_vr[k]
    temp = np.sum(prod)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel/__main__.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  app.launch_new_instance()


In [72]:
test_sensitivity = (test_vl * test_vr) / temp

In [75]:
test_sensitivity

array([ -0.00000000e+00 -0.00000000e+00j,
        -1.11719027e+20 -0.00000000e+00j,
         1.17626853e+20 -0.00000000e+00j,
        -1.07680951e+19 +2.16739743e+19j,
        -1.07680951e+19 -2.16739743e+19j,
         1.52903165e+19 +2.39402074e+19j,
         1.52903165e+19 -2.39402074e+19j,
        -3.58858940e+16 -2.08656245e+19j,
        -3.58858940e+16 +2.08656245e+19j,
        -5.36312502e+11 -1.60793905e+12j,
        -5.36312502e+11 +1.60793905e+12j,   1.00000000e+00 -0.00000000e+00j])

In [80]:
np.alen(test_vec)

12

In [ ]:
test_eigdom = np.max(abs(test_eig_vals))

In [84]:
test_eigdom

1.7660984615448272

In [ ]:
test_elasticity = test_sensitivity * (l_m/test_eigdom)

In [87]:
test_elasticity

array([[  0.00000000e+00 -0.00000000e+00j,
         -1.26515061e+20 -0.00000000e+00j,
          3.33013293e+19 +0.00000000e+00j,
         -1.21942183e+19 +2.45444688e+19j,
         -3.04855457e+18 -6.13611720e+18j,
          1.73153613e+19 +2.71108411e+19j,
          4.32884034e+18 -6.77771028e+18j,
         -4.06386108e+16 -2.36290615e+19j,
         -1.01596527e+16 +5.90726536e+18j,
         -6.07341565e+11 -1.82089400e+12j,
         -1.51835391e+11 +4.55223500e+11j,
          0.00000000e+00 +0.00000000e+00j],
       [  0.00000000e+00 -0.00000000e+00j,
          0.00000000e+00 -0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
         -0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 -0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 -0.00000000e+00j,
         -0.00000000e+00 +0.00000000e+00j,
          0.00000000e+00 -0.00000000e+00j,
         -0.00000000e+00 +0.00000000e+00j,
          